const MySkills=[
    {
        id:1,
        image:"../../images/skills/C.png",
        rating:"⭐⭐⭐⭐"
    },
    {
        id:2,
    
        image:"../../images/skills/C++.png",
        rating:"⭐⭐⭐⭐"
    },
    {
        id:3,
        image:"../../images/skills/java.png",
        rating:"⭐⭐⭐"
    },
    {
        id:4,
        image:"../../images/skills/python.png",
        rating:"⭐⭐⭐⭐"
    },
    {
        id:5,
        image:"../../images/skills/HTML.png",
        rating:"⭐⭐⭐⭐⭐"
    },
    {
        id:6,
        image:"../../images/skills/CSS.png",
        rating:"⭐⭐⭐⭐"
    },
    {
        id:7,
        image:"../../images/skills/bootstrap.png",
        rating:"⭐⭐⭐⭐"
    },
    {
        id:8,
        image:"../../images/skills/javascript.png",
        rating:"⭐⭐⭐⭐"
    },
    {
        id:9,
        image:"../../images/skills/jquery.png",
        rating:"⭐⭐⭐⭐"
    },
    {
        id:10,
        image:"../../images/skills/react.png",
        rating:"⭐⭐⭐⭐"
    },
    {
        id:11,
        image:"../../images/skills/node-js.png",
        rating:"⭐⭐⭐⭐"
    },
    {
        id:12,
        image:"../../images/skills/API.png",
        rating:"⭐⭐⭐⭐⭐"
    },
    {
        id:13,
        image:"../../images/skills/sql.png",
        rating:"⭐⭐⭐⭐"
    },
    {
        id:14,
        image:"../../images/skills/mongodb.png",
        rating:"⭐⭐⭐"
    },
    {
        id:15,
        image:"../../images/skills/AI.png",
        rating:"⭐⭐"
    },
    {
        id:16,
        image:"../../images/skills/DSA.png",
        rating:"⭐⭐⭐"
    },
    {
        id:17,
        image:"../../images/skills/blockchain.png",
        rating:"⭐⭐⭐"
    },
    {
        id:18,
        image:"../../images/skills/github.png",
        rating:"⭐⭐⭐"
    },
    {
        id:19,
        image:"../../images/skills/typing.png",
        rating:"⭐⭐⭐"
    },
    {
        id:20,
        image:"../../images/skills/piano.png",
        rating:"⭐⭐⭐"
    }
]

export default MySkills;